version: "3.8"

services:
  backend:
    build: ./backend
    container_name: sprint-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: sprint-frontend
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: sprint-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: always
